---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:
  
    # Download .deb file from artifacts.elastic.com
  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    # Install .deb file using dpkg
  - name: install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb
	
    # Copy filebeat config file to remote servers
  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml
	  
    # Run filebeat modules enable system command
  - name: enable and configure system module
    command: filebeat modules enable system

    # Run filebeat setup command
  - name: setup filebeat
    command: filebeat setup
	
    # Start the filebeat service
  - name: start filebeat service
    command: service filebeat start
	
    # Use systemd module to start filebeat on startup
  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes