---
- name: Installing and Launching Metricbeat
  hosts: webservers
  become: yes
  tasks:

    # Download .deb file from artifacts.elastic.co
  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    # Install .deb file using dpkg
  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb

    # Copy metricbeat config file to remote servers
  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Run metricbeat modules enable system command
  - name: enable and configure system module
    command: metricbeat modules enable docker

    # Run metricbeat setup command
  - name: setup metricbeat
    command: metricbeat setup

    # Start the metricbeat service
  - name: start metricbeat service
    command: service metricbeat start

    # Use systemd module to start metricbeat on startup
  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes